### ISSUE TITLE
502 error on the incidents page

### ISSUE THREAD

**Issue by dyeoman2** [quirrel-dev/quirrel.dev#468]
## Bug Report

**Current Behavior**
I get this error "502 An unexpected error has occurred." when I navigate to https://quirrel.dev/projects/Omnilocal/environments/Prod/incidents 

**Environment**
- Quirrel version: v1.8.1
- Node/npm version: v17.5.0

**Comment by dyeoman2** [comment]
It is still happening for me. Here are some more details. Thank you.

Request URL: https://quirrel.dev/api/incidents/queries/getIncidents
Request Method: POST
Status Code: 502 
Response Date: Thu, 10 Mar 2022 00:14:50 GMT
Response Body:
```
{
  "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).",
  "errorType": "Function.ResponseSizeTooLarge"
}
```

**Comment by Skn0tt** [comment]
awesome, that's super helpful! I opened a PR that tries fixing this: #470 can you check https://deploy-preview-470--quirrel-dashboard.netlify.app and see if that fixes your issue?

**Comment by dyeoman2** [comment]
That worked. Thanks @Skn0tt!
